export interface OTProfile {
  id: string;
  slug: string;
  name: string;
  titleHe: string;
  city: string;
  photo: string;
  specialties: string[];
  insurance: string[];
  languages: string[];
  sessionTypes: string[];
  feePerSession: number;
  bio: string;
  phone: string;
  acceptingNewPatients: boolean;
  isPro: boolean;
}

export const MOCK_OTS: OTProfile[] = [
  {
    id: '1',
    slug: 'michal-cohen',
    name: 'מיכל כהן',
    titleHe: 'מרפאה בעיסוק',
    city: 'תל אביב',
    photo: 'https://i.pravatar.cc/150?u=michal-cohen',
    specialties: ['paediatrics', 'sensoryProcessing'],
    insurance: ['clalit', 'maccabi', 'private'],
    languages: ['he', 'en'],
    sessionTypes: ['inPerson', 'telehealth'],
    feePerSession: 420,
    bio: 'מרפאה בעיסוק מוסמכת עם ניסיון של 10 שנים בטיפול בילדים עם קשיי עיבוד חושי ועיכובים התפתחותיים. מתמחה בגישה מבוססת משחק ובשיתוף פעולה הדוק עם הורים ומסגרות חינוכיות. בוגרת אוניברסיטת תל אביב עם תואר שני בריפוי בעיסוק.',
    phone: '050-123-4567',
    acceptingNewPatients: true,
    isPro: true,
  },
  {
    id: '2',
    slug: 'yosef-levi',
    name: 'יוסף לוי',
    titleHe: 'מרפא בעיסוק',
    city: 'ירושלים',
    photo: 'https://i.pravatar.cc/150?u=yosef-levi',
    specialties: ['neuro', 'geriatrics'],
    insurance: ['clalit', 'leumit', 'meuhedet', 'private'],
    languages: ['he', 'ar', 'en'],
    sessionTypes: ['inPerson', 'homeVisit'],
    feePerSession: 380,
    bio: 'מרפא בעיסוק עם התמחות בשיקום נוירולוגי וטיפול בקשישים. עובד עם מטופלים לאחר שבץ מוחי, פרקינסון ופגיעות ראש. מאמין בגישה הוליסטית המשלבת פעילויות יומיומיות לשיפור עצמאות המטופל.',
    phone: '052-234-5678',
    acceptingNewPatients: true,
    isPro: true,
  },
  {
    id: '3',
    slug: 'sarah-mizrahi',
    name: 'שרה מזרחי',
    titleHe: 'מרפאה בעיסוק',
    city: 'חיפה',
    photo: 'https://i.pravatar.cc/150?u=sarah-mizrahi',
    specialties: ['mentalHealth', 'paediatrics'],
    insurance: ['maccabi', 'meuhedet', 'private'],
    languages: ['he', 'ru'],
    sessionTypes: ['inPerson', 'telehealth'],
    feePerSession: 400,
    bio: 'מרפאה בעיסוק המתמחה בבריאות הנפש ובטיפול בילדים עם הפרעות קשב וריכוז וחרדה. עובדת בגישה קוגניטיבית-התנהגותית ומשלבת כלים מעולם הריפוי בעיסוק. בוגרת אוניברסיטת חיפה ובעלת 8 שנות ניסיון קליני.',
    phone: '054-345-6789',
    acceptingNewPatients: false,
    isPro: true,
  },
  {
    id: '4',
    slug: 'david-peretz',
    name: 'דוד פרץ',
    titleHe: 'מרפא בעיסוק',
    city: 'באר שבע',
    photo: 'https://i.pravatar.cc/150?u=david-peretz',
    specialties: ['handTherapy', 'neuro'],
    insurance: ['clalit', 'maccabi', 'leumit', 'private'],
    languages: ['he', 'en'],
    sessionTypes: ['inPerson'],
    feePerSession: 350,
    bio: 'מרפא בעיסוק מוסמך לטיפול ביד עם ניסיון נרחב בשיקום לאחר פציעות כף יד, שורש כף יד וגפה עליונה. עבד במשך 5 שנים בבית חולים סורוקה לפני פתיחת מרפאה פרטית. מספק טיפולים ממוקדי מטרה המחזירים את המטופל לתפקוד מלא.',
    phone: '058-456-7890',
    acceptingNewPatients: true,
    isPro: false,
  },
  {
    id: '5',
    slug: 'noa-goldstein',
    name: 'נועה גולדשטיין',
    titleHe: 'מרפאה בעיסוק',
    city: 'ראשון לציון',
    photo: 'https://i.pravatar.cc/150?u=noa-goldstein',
    specialties: ['paediatrics', 'sensoryProcessing', 'mentalHealth'],
    insurance: ['maccabi', 'private'],
    languages: ['he', 'en', 'ru'],
    sessionTypes: ['inPerson', 'telehealth', 'homeVisit'],
    feePerSession: 450,
    bio: 'מרפאה בעיסוק המתמחה בטיפול בילדים על הספקטרום האוטיסטי ובעלי צרכים מיוחדים. בעלת הכשרה בשיטת SIT לאינטגרציה חושית ובגישת DIR/Floortime. עורכת הערכות מקיפות ומותאמות אישית לכל ילד.',
    phone: '050-567-8901',
    acceptingNewPatients: true,
    isPro: true,
  },
  {
    id: '6',
    slug: 'omar-hassan',
    name: 'עומר חסן',
    titleHe: 'מרפא בעיסוק',
    city: 'נתניה',
    photo: 'https://i.pravatar.cc/150?u=omar-hassan',
    specialties: ['neuro', 'geriatrics', 'handTherapy'],
    insurance: ['clalit', 'meuhedet', 'leumit', 'private'],
    languages: ['he', 'ar', 'en'],
    sessionTypes: ['inPerson', 'homeVisit'],
    feePerSession: 370,
    bio: 'מרפא בעיסוק דו-לשוני עם ניסיון בשיקום נוירולוגי וגריאטרי. מתמחה בהערכת ושיקום פעילויות חיי יומיום לקשישים ולאנשים עם מגבלות תפקודיות. מספק שירותים בעברית ובערבית ומשרת קהילות שונות במרכז הארץ.',
    phone: '052-678-9012',
    acceptingNewPatients: true,
    isPro: false,
  },
  {
    id: '7',
    slug: 'rivka-shapiro',
    name: 'רבקה שפירו',
    titleHe: 'מרפאה בעיסוק',
    city: 'פתח תקווה',
    photo: 'https://i.pravatar.cc/150?u=rivka-shapiro',
    specialties: ['mentalHealth', 'geriatrics'],
    insurance: ['clalit', 'maccabi', 'meuhedet', 'leumit', 'private'],
    languages: ['he', 'en'],
    sessionTypes: ['inPerson', 'telehealth'],
    feePerSession: 410,
    bio: 'מרפאה בעיסוק עם התמחות כפולה בבריאות הנפש וטיפול בקשישים. מעניקה טיפול אינטגרטיבי הכולל פעילויות יומיומיות, ניהול זמן והתמודדות עם אתגרים רגשיים. מחויבת לגישה מכבדת ומעצימה לכל מטופל.',
    phone: '054-789-0123',
    acceptingNewPatients: false,
    isPro: true,
  },
  {
    id: '8',
    slug: 'amit-bar',
    name: 'עמית בר',
    titleHe: 'מרפא בעיסוק',
    city: 'אשדוד',
    photo: 'https://i.pravatar.cc/150?u=amit-bar',
    specialties: ['paediatrics', 'sensoryProcessing'],
    insurance: ['maccabi', 'leumit', 'private'],
    languages: ['he', 'ru', 'en'],
    sessionTypes: ['inPerson', 'homeVisit'],
    feePerSession: 360,
    bio: 'מרפא בעיסוק המתמחה בטיפול בילדים עם לקויות למידה ועיכובים התפתחותיים. עובד בשיתוף פעולה עם בתי ספר ומסגרות חינוכיות לבניית תוכניות תמיכה מקיפות. בוגר הטכניון ובעל הסמכות בינלאומיות בטיפול חושי.',
    phone: '058-890-1234',
    acceptingNewPatients: true,
    isPro: false,
  },
  {
    id: '9',
    slug: 'tamar-klein',
    name: 'תמר קליין',
    titleHe: 'מרפאה בעיסוק',
    city: 'הרצליה',
    photo: 'https://i.pravatar.cc/150?u=tamar-klein',
    specialties: ['handTherapy', 'neuro'],
    insurance: ['maccabi', 'private'],
    languages: ['he', 'en'],
    sessionTypes: ['inPerson', 'telehealth'],
    feePerSession: 550,
    bio: 'מרפאה בעיסוק מומחית לטיפול ביד עם תואר שני ממכון ויצמן. מתמחה בטיפול כירורגי ושמרני של גפה עליונה כולל שחזור עצבים ורצועות. נותנת שירות ברמה גבוהה ותוצאות מוכחות לחזרה מהירה לתפקוד.',
    phone: '050-901-2345',
    acceptingNewPatients: true,
    isPro: true,
  },
  {
    id: '10',
    slug: 'eitan-amir',
    name: 'איתן אמיר',
    titleHe: 'מרפא בעיסוק',
    city: 'רמת גן',
    photo: 'https://i.pravatar.cc/150?u=eitan-amir',
    specialties: ['neuro', 'mentalHealth', 'geriatrics'],
    insurance: ['clalit', 'meuhedet', 'private'],
    languages: ['he', 'en'],
    sessionTypes: ['inPerson', 'telehealth', 'homeVisit'],
    feePerSession: 430,
    bio: 'מרפא בעיסוק בעל ניסיון של 12 שנים בשיקום נוירולוגי ובריאות הנפש. עובד עם מגוון אוכלוסיות כולל ניצולי שבץ, מטופלי פסיכיאטריה וקשישים. מאמין בגישה ממוקדת-מטופל ומשלב טכנולוגיות שיקום חדשניות בטיפול.',
    phone: '052-012-3456',
    acceptingNewPatients: true,
    isPro: false,
  },
  {
    id: '11',
    slug: 'hana-nachmani',
    name: 'חנה נחמני',
    titleHe: 'מרפאה בעיסוק',
    city: 'תל אביב',
    photo: 'https://i.pravatar.cc/150?u=hana-nachmani',
    specialties: ['mentalHealth', 'paediatrics', 'sensoryProcessing'],
    insurance: ['maccabi', 'meuhedet', 'leumit', 'private'],
    languages: ['he', 'en', 'ar'],
    sessionTypes: ['inPerson', 'telehealth'],
    feePerSession: 480,
    bio: 'מרפאה בעיסוק מנוסה המתמחה בבריאות הנפש ובטיפול ילדים רב-תרבותי. בעלת הכשרה מיוחדת בטיפול בטראומה ובגישות מבוססות מיינדפולנס. עובדת עם ילדים, מתבגרים ומבוגרים בגישה תרפויטית חמה ומכבדת.',
    phone: '054-123-4568',
    acceptingNewPatients: false,
    isPro: true,
  },
  {
    id: '12',
    slug: 'moshe-ben-david',
    name: 'משה בן דוד',
    titleHe: 'מרפא בעיסוק',
    city: 'ירושלים',
    photo: 'https://i.pravatar.cc/150?u=moshe-ben-david',
    specialties: ['geriatrics', 'neuro', 'handTherapy'],
    insurance: ['clalit', 'maccabi', 'leumit', 'private'],
    languages: ['he', 'en'],
    sessionTypes: ['inPerson', 'homeVisit'],
    feePerSession: 395,
    bio: 'מרפא בעיסוק ותיק עם ניסיון של 15 שנים בגריאטריה ושיקום נוירולוגי. מתמחה בהערכת בטיחות בית ובהתאמת עזרי שיקום לקשישים. מספק טיפולי בית ומחויב לשמירת עצמאות המטופל הקשיש.',
    phone: '058-234-5679',
    acceptingNewPatients: true,
    isPro: false,
  },
];

export function getOTBySlug(slug: string): OTProfile | undefined {
  return MOCK_OTS.find((ot) => ot.slug === slug);
}
