/**
 * Seed script — populates the database with sample OT profiles.
 * Run: npx tsx scripts/seed.ts
 *
 * Idempotent: upserts by slug so it's safe to run multiple times.
 */

import 'dotenv/config';
import mongoose from 'mongoose';
import { OTProfile } from '../src/lib/db/models/OTProfile';

const MONGODB_URI = process.env.MONGODB_URI ?? 'mongodb://localhost:27017/otsearch';

const profiles = [
  {
    slug: 'michal-cohen',
    displayName: { he: 'מיכל כהן', ar: 'ميخال كوهين', en: 'Michal Cohen' },
    bio: {
      he: 'מרפאה בעיסוק מוסמכת עם ניסיון של 10 שנים בטיפול בילדים עם קשיי עיבוד חושי ועיכובים התפתחותיים. מתמחה בגישה מבוססת משחק ובשיתוף פעולה הדוק עם הורים ומסגרות חינוכיות.',
      ar: 'معالجة وظيفية معتمدة بخبرة 10 سنوات في علاج الأطفال الذين يعانون من صعوبات المعالجة الحسية والتأخرات في النمو.',
      en: 'Certified occupational therapist with 10 years of experience treating children with sensory processing difficulties and developmental delays. Specialises in play-based approaches.',
    },
    photo: 'https://i.pravatar.cc/150?u=michal-cohen',
    mohRegistrationNumber: 'MOH-12345',
    specialisations: ['paediatrics', 'sensory-processing'],
    languages: ['he', 'en'],
    location: { type: 'Point' as const, coordinates: [34.7818, 32.0853], city: 'תל אביב', address: 'רחוב דיזנגוף 120, תל אביב' },
    sessionTypes: ['in-person', 'telehealth'],
    insuranceAccepted: ['clalit', 'maccabi', 'private'],
    feeRange: { min: 400, max: 450, currency: 'ILS' as const },
    contactEmail: 'michal.cohen@therapio.co.il',
    contactPhone: '050-123-4567',
    subscriptionTier: 'premium' as const,
    isFeatured: true,
    isAcceptingPatients: true,
  },
  {
    slug: 'yosef-levi',
    displayName: { he: 'יוסף לוי', ar: 'يوسف ليفي', en: 'Yosef Levi' },
    bio: {
      he: 'מרפא בעיסוק עם התמחות בשיקום נוירולוגי וטיפול בקשישים. עובד עם מטופלים לאחר שבץ מוחי, פרקינסון ופגיעות ראש.',
      ar: 'معالج وظيفي متخصص في إعادة التأهيل العصبي وعلاج كبار السن. يعمل مع مرضى ما بعد السكتة الدماغية.',
      en: 'OT specialising in neurological rehabilitation and elderly care. Works with post-stroke, Parkinson\'s and TBI patients.',
    },
    photo: 'https://i.pravatar.cc/150?u=yosef-levi',
    mohRegistrationNumber: 'MOH-23456',
    specialisations: ['neurological', 'geriatrics'],
    languages: ['he', 'ar', 'en'],
    location: { type: 'Point' as const, coordinates: [35.2137, 31.7683], city: 'ירושלים', address: 'רחוב יפו 80, ירושלים' },
    sessionTypes: ['in-person', 'home-visit'],
    insuranceAccepted: ['clalit', 'leumit', 'meuhedet', 'private'],
    feeRange: { min: 360, max: 400, currency: 'ILS' as const },
    contactEmail: 'yosef.levi@therapio.co.il',
    contactPhone: '052-234-5678',
    subscriptionTier: 'premium' as const,
    isFeatured: true,
    isAcceptingPatients: true,
  },
  {
    slug: 'sara-mizrahi',
    displayName: { he: 'שרה מזרחי', ar: 'سارة مزراحي', en: 'Sara Mizrahi' },
    bio: {
      he: 'מרפאה בעיסוק המתמחה בבריאות הנפש ובטיפול בילדים עם הפרעות קשב וריכוז וחרדה. עובדת בגישה קוגניטיבית-התנהגותית.',
      ar: 'معالجة وظيفية متخصصة في الصحة النفسية وعلاج الأطفال الذين يعانون من اضطراب نقص الانتباه.',
      en: 'OT specialising in mental health and children with ADHD and anxiety disorders. Uses cognitive-behavioural approaches.',
    },
    photo: 'https://i.pravatar.cc/150?u=sara-mizrahi',
    mohRegistrationNumber: 'MOH-34567',
    specialisations: ['mental-health', 'paediatrics'],
    languages: ['he', 'ru'],
    location: { type: 'Point' as const, coordinates: [34.9896, 32.7940], city: 'חיפה', address: 'שדרות הנשיא 50, חיפה' },
    sessionTypes: ['in-person', 'telehealth'],
    insuranceAccepted: ['maccabi', 'meuhedet', 'private'],
    feeRange: { min: 380, max: 420, currency: 'ILS' as const },
    contactEmail: 'sara.mizrahi@therapio.co.il',
    contactPhone: '054-345-6789',
    subscriptionTier: 'premium' as const,
    isFeatured: false,
    isAcceptingPatients: false,
  },
  {
    slug: 'david-peretz',
    displayName: { he: 'דוד פרץ', ar: 'ديفيد بيرتس', en: 'David Peretz' },
    bio: {
      he: 'מרפא בעיסוק מומחה לטיפול ביד ושיקום נוירולוגי. בעל ניסיון נרחב בטיפול בפציעות ספורט ותאונות עבודה.',
      ar: 'معالج وظيفي خبير في علاج اليد وإعادة التأهيل العصبي مع خبرة واسعة في إصابات الرياضة.',
      en: 'OT expert in hand therapy and neurological rehabilitation with extensive experience in sports injuries and work accidents.',
    },
    photo: 'https://i.pravatar.cc/150?u=david-peretz',
    mohRegistrationNumber: 'MOH-45678',
    specialisations: ['hand-therapy', 'neurological'],
    languages: ['he', 'en'],
    location: { type: 'Point' as const, coordinates: [34.7913, 31.2520], city: 'באר שבע', address: 'שדרות רגר 110, באר שבע' },
    sessionTypes: ['in-person'],
    insuranceAccepted: ['clalit', 'maccabi', 'leumit', 'private'],
    feeRange: { min: 350, max: 380, currency: 'ILS' as const },
    contactEmail: 'david.peretz@therapio.co.il',
    contactPhone: '058-456-7890',
    subscriptionTier: 'free' as const,
    isFeatured: false,
    isAcceptingPatients: true,
  },
  {
    slug: 'hana-shapira',
    displayName: { he: 'חנה שפירא', ar: 'حنا شابيرا', en: 'Hana Shapira' },
    bio: {
      he: 'מרפאה בעיסוק עם התמחות בגריאטריה ושיקום לאחר ניתוח. מסייעת לקשישים לשמור על עצמאות ואיכות חיים.',
      ar: 'معالجة وظيفية متخصصة في رعاية كبار السن وإعادة التأهيل بعد الجراحة.',
      en: 'OT specialising in geriatrics and post-surgical rehabilitation, helping elderly patients maintain independence and quality of life.',
    },
    photo: 'https://i.pravatar.cc/150?u=hana-shapira',
    mohRegistrationNumber: 'MOH-56789',
    specialisations: ['geriatrics', 'neurological'],
    languages: ['he', 'en', 'ru'],
    location: { type: 'Point' as const, coordinates: [34.8516, 32.3215], city: 'נתניה', address: 'רחוב הרצל 55, נתניה' },
    sessionTypes: ['in-person', 'home-visit', 'telehealth'],
    insuranceAccepted: ['clalit', 'maccabi', 'meuhedet', 'leumit', 'private'],
    feeRange: { min: 350, max: 400, currency: 'ILS' as const },
    contactEmail: 'hana.shapira@therapio.co.il',
    contactPhone: '050-567-8901',
    subscriptionTier: 'premium' as const,
    isFeatured: true,
    isAcceptingPatients: true,
  },
  {
    slug: 'amir-hassan',
    displayName: { he: 'עמיר חסן', ar: 'عامر حسن', en: 'Amir Hassan' },
    bio: {
      he: 'מרפא בעיסוק דובר ערבית ועברית, מתמחה בטיפול בילדים ובני נוער עם לקויות התפתחותיות. מעניק שירות בצפון הארץ.',
      ar: 'معالج وظيفي يتحدث العربية والعبرية، متخصص في علاج الأطفال والمراهقين الذين يعانون من إعاقات في النمو.',
      en: 'Arabic and Hebrew-speaking OT specialising in children and adolescents with developmental disabilities. Serves northern Israel.',
    },
    photo: 'https://i.pravatar.cc/150?u=amir-hassan',
    mohRegistrationNumber: 'MOH-67890',
    specialisations: ['paediatrics', 'sensory-processing', 'mental-health'],
    languages: ['ar', 'he', 'en'],
    location: { type: 'Point' as const, coordinates: [35.1041, 32.9181], city: 'נצרת', address: 'רחוב פאולוס השישי 12, נצרת' },
    sessionTypes: ['in-person', 'telehealth'],
    insuranceAccepted: ['clalit', 'maccabi', 'meuhedet', 'leumit'],
    feeRange: { min: 330, max: 370, currency: 'ILS' as const },
    contactEmail: 'amir.hassan@therapio.co.il',
    contactPhone: '052-678-9012',
    subscriptionTier: 'free' as const,
    isFeatured: false,
    isAcceptingPatients: true,
  },
  {
    slug: 'rivka-goldman',
    displayName: { he: 'רבקה גולדמן', ar: 'ريفكا غولدمان', en: 'Rivka Goldman' },
    bio: {
      he: 'מרפאה בעיסוק בתחום הארגונומיה ושיקום תעסוקתי. מסייעת לעובדים עם פציעות עבודה ומחלות מקצוע לחזור לתפקוד מלא.',
      ar: 'معالجة وظيفية في مجال الإرغونوميا وإعادة التأهيل المهني. تساعد العمال المصابين على استعادة وظائفهم الكاملة.',
      en: 'OT specialising in ergonomics and vocational rehabilitation, helping injured workers return to full function and employment.',
    },
    photo: 'https://i.pravatar.cc/150?u=rivka-goldman',
    mohRegistrationNumber: 'MOH-78901',
    specialisations: ['ergonomic', 'vocational'],
    languages: ['he', 'en'],
    location: { type: 'Point' as const, coordinates: [34.7818, 32.0853], city: 'תל אביב', address: 'רחוב שלמה המלך 8, תל אביב' },
    sessionTypes: ['in-person', 'telehealth'],
    insuranceAccepted: ['maccabi', 'private'],
    feeRange: { min: 450, max: 550, currency: 'ILS' as const },
    contactEmail: 'rivka.goldman@therapio.co.il',
    contactPhone: '054-789-0123',
    subscriptionTier: 'premium' as const,
    isFeatured: false,
    isAcceptingPatients: true,
  },
  {
    slug: 'noa-katz',
    displayName: { he: 'נועה כץ', ar: 'نوعا كاتس', en: 'Noa Katz' },
    bio: {
      he: 'מרפאה בעיסוק מתמחה בריפוי ביד ופציעות יד. בעלת תעודת הכשרה בינלאומית ב-CHT. מטפלת גם בפציעות ספורט.',
      ar: 'معالجة وظيفية متخصصة في علاج اليد وإصابات اليد. حاصلة على شهادة دولية في العلاج اليدوي.',
      en: 'OT specialising in hand therapy and hand injuries with international CHT certification. Also treats sports-related injuries.',
    },
    photo: 'https://i.pravatar.cc/150?u=noa-katz',
    mohRegistrationNumber: 'MOH-89012',
    specialisations: ['hand-therapy'],
    languages: ['he', 'en', 'fr'],
    location: { type: 'Point' as const, coordinates: [34.9896, 32.7940], city: 'חיפה', address: 'רחוב ממשי 25, חיפה' },
    sessionTypes: ['in-person'],
    insuranceAccepted: ['clalit', 'maccabi', 'meuhedet', 'leumit', 'private'],
    feeRange: { min: 420, max: 480, currency: 'ILS' as const },
    contactEmail: 'noa.katz@therapio.co.il',
    contactPhone: '050-890-1234',
    subscriptionTier: 'free' as const,
    isFeatured: false,
    isAcceptingPatients: true,
  },
  {
    slug: 'eli-ben-david',
    displayName: { he: 'אלי בן דוד', ar: 'إيلي بن ديفيد', en: 'Eli Ben David' },
    bio: {
      he: 'מרפא בעיסוק בעל ניסיון של 15 שנה בשיקום ילדים עם שיתוק מוחי וצרכים מיוחדים. עובד בשיתוף פעולה עם גנים ובתי ספר.',
      ar: 'معالج وظيفي بخبرة 15 عامًا في إعادة تأهيل الأطفال المصابين بالشلل الدماغي.',
      en: 'OT with 15 years of experience in rehabilitation of children with cerebral palsy and special needs, collaborating with schools.',
    },
    photo: 'https://i.pravatar.cc/150?u=eli-ben-david',
    mohRegistrationNumber: 'MOH-90123',
    specialisations: ['paediatrics', 'neurological', 'sensory-processing'],
    languages: ['he'],
    location: { type: 'Point' as const, coordinates: [34.8983, 32.1663], city: 'רמת גן', address: 'שדרות ירושלים 30, רמת גן' },
    sessionTypes: ['in-person', 'telehealth'],
    insuranceAccepted: ['clalit', 'meuhedet', 'private'],
    feeRange: { min: 380, max: 420, currency: 'ILS' as const },
    contactEmail: 'eli.bendavid@therapio.co.il',
    contactPhone: '052-901-2345',
    subscriptionTier: 'free' as const,
    isFeatured: false,
    isAcceptingPatients: true,
  },
  {
    slug: 'fatima-abu-ali',
    displayName: { he: 'פאטמה אבו עלי', ar: 'فاطمة أبو علي', en: 'Fatima Abu Ali' },
    bio: {
      he: 'מרפאה בעיסוק ערבייה המתמחה בטיפול בנשים ובילדים. מעניקה שירות בעברית ובערבית במגזר הערבי ובמעורב.',
      ar: 'معالجة وظيفية متخصصة في علاج النساء والأطفال. تقدم الخدمة باللغة العربية والعبرية في المجتمعات العربية والمختلطة.',
      en: 'Arabic OT specialising in women\'s and children\'s care. Provides services in both Arabic and Hebrew across mixed communities.',
    },
    photo: 'https://i.pravatar.cc/150?u=fatima-abu-ali',
    mohRegistrationNumber: 'MOH-01234',
    specialisations: ['paediatrics', 'mental-health'],
    languages: ['ar', 'he'],
    location: { type: 'Point' as const, coordinates: [35.2137, 31.7683], city: 'ירושלים', address: 'שכונת בית צפאפא, ירושלים' },
    sessionTypes: ['in-person', 'home-visit'],
    insuranceAccepted: ['clalit', 'maccabi', 'meuhedet', 'leumit'],
    feeRange: { min: 320, max: 360, currency: 'ILS' as const },
    contactEmail: 'fatima.abuali@therapio.co.il',
    contactPhone: '054-012-3456',
    subscriptionTier: 'free' as const,
    isFeatured: false,
    isAcceptingPatients: true,
  },
  {
    slug: 'tamar-roi',
    displayName: { he: 'תמר רועי', ar: 'تامار روعي', en: 'Tamar Roi' },
    bio: {
      he: 'מרפאה בעיסוק מתמחה בריפוי בעיסוק פסיכיאטרי ותמיכה בבריאות הנפש. עובדת עם מבוגרים הסובלים מדיכאון, חרדה ומשבר.',
      ar: 'معالجة وظيفية متخصصة في علاج اضطرابات نفسية تعمل مع البالغين الذين يعانون من الاكتئاب والقلق.',
      en: 'OT specialising in psychiatric occupational therapy and mental health support, working with adults facing depression and anxiety.',
    },
    photo: 'https://i.pravatar.cc/150?u=tamar-roi',
    mohRegistrationNumber: 'MOH-11234',
    specialisations: ['mental-health'],
    languages: ['he', 'en'],
    location: { type: 'Point' as const, coordinates: [34.7818, 32.0853], city: 'תל אביב', address: 'רחוב בן יהודה 45, תל אביב' },
    sessionTypes: ['in-person', 'telehealth'],
    insuranceAccepted: ['maccabi', 'meuhedet', 'private'],
    feeRange: { min: 400, max: 450, currency: 'ILS' as const },
    contactEmail: 'tamar.roi@therapio.co.il',
    contactPhone: '050-112-2334',
    subscriptionTier: 'free' as const,
    isFeatured: false,
    isAcceptingPatients: false,
  },
  {
    slug: 'ron-ofer',
    displayName: { he: 'רון עופר', ar: 'رون عوفر', en: 'Ron Ofer' },
    bio: {
      he: 'מרפא בעיסוק בתחום הארגונומיה התעסוקתית. מסייע לארגונים להתאים את סביבת העבודה ולמנוע פציעות חוזרות.',
      ar: 'معالج وظيفي في مجال الإرغونوميا المهنية. يساعد المؤسسات على تكييف بيئة العمل ومنع الإصابات المتكررة.',
      en: 'OT in occupational ergonomics, helping organisations adapt work environments and prevent repetitive strain injuries.',
    },
    photo: 'https://i.pravatar.cc/150?u=ron-ofer',
    mohRegistrationNumber: 'MOH-22345',
    specialisations: ['ergonomic', 'vocational'],
    languages: ['he', 'en'],
    location: { type: 'Point' as const, coordinates: [34.7818, 32.0853], city: 'תל אביב', address: 'דרך מנחם בגין 23, תל אביב' },
    sessionTypes: ['in-person', 'telehealth'],
    insuranceAccepted: ['private'],
    feeRange: { min: 500, max: 600, currency: 'ILS' as const },
    contactEmail: 'ron.ofer@therapio.co.il',
    contactPhone: '052-223-3445',
    subscriptionTier: 'premium' as const,
    isFeatured: false,
    isAcceptingPatients: true,
  },
  {
    slug: 'orna-friedman',
    displayName: { he: 'אורנה פרידמן', ar: 'أورنا فريدمان', en: 'Orna Friedman' },
    bio: {
      he: 'מרפאה בעיסוק בכירה עם 20 שנות ניסיון בשיקום נוירולוגי לאחר שבץ ופגיעות ראש. מדריכה ומנחה קלינית.',
      ar: 'معالجة وظيفية أولى بخبرة 20 عامًا في إعادة التأهيل العصبي بعد السكتة الدماغية وإصابات الرأس.',
      en: 'Senior OT with 20 years in neurological rehabilitation post-stroke and TBI. Clinical trainer and supervisor.',
    },
    photo: 'https://i.pravatar.cc/150?u=orna-friedman',
    mohRegistrationNumber: 'MOH-33456',
    specialisations: ['neurological', 'geriatrics'],
    languages: ['he', 'en', 'ru'],
    location: { type: 'Point' as const, coordinates: [34.8516, 32.3215], city: 'נתניה', address: 'רחוב הרצל 20, נתניה' },
    sessionTypes: ['in-person', 'telehealth'],
    insuranceAccepted: ['clalit', 'maccabi', 'meuhedet', 'leumit', 'private'],
    feeRange: { min: 450, max: 520, currency: 'ILS' as const },
    contactEmail: 'orna.friedman@therapio.co.il',
    contactPhone: '054-334-4556',
    subscriptionTier: 'premium' as const,
    isFeatured: true,
    isAcceptingPatients: true,
  },
  {
    slug: 'gal-bar-oz',
    displayName: { he: 'גל בר-אוז', ar: 'غال بار-أوز', en: 'Gal Bar-Oz' },
    bio: {
      he: 'מרפאה בעיסוק המתמחה בטיפול בגיל הרך — ילדים עד גיל 6. עובדת עם עיכובים בדיבור, מוטוריקה ואינטגרציה חושית.',
      ar: 'معالجة وظيفية متخصصة في رعاية الأطفال الصغار حتى سن 6 سنوات.',
      en: 'OT specialising in early childhood — children up to age 6 — covering speech delays, motor skills, and sensory integration.',
    },
    photo: 'https://i.pravatar.cc/150?u=gal-bar-oz',
    mohRegistrationNumber: 'MOH-44567',
    specialisations: ['paediatrics', 'sensory-processing'],
    languages: ['he'],
    location: { type: 'Point' as const, coordinates: [34.9024, 32.0819], city: 'פתח תקווה', address: 'שדרות זבוטינסקי 100, פתח תקווה' },
    sessionTypes: ['in-person', 'home-visit'],
    insuranceAccepted: ['clalit', 'maccabi', 'meuhedet', 'private'],
    feeRange: { min: 360, max: 400, currency: 'ILS' as const },
    contactEmail: 'gal.baroz@therapio.co.il',
    contactPhone: '050-445-5667',
    subscriptionTier: 'free' as const,
    isFeatured: false,
    isAcceptingPatients: true,
  },
  {
    slug: 'moshe-dvir',
    displayName: { he: 'משה דביר', ar: 'موشيه دفير', en: 'Moshe Dvir' },
    bio: {
      he: 'מרפא בעיסוק מומחה לשיקום תעסוקתי ושוק העבודה. מסייע לאנשים עם מוגבלויות להשתלב בשוק העבודה.',
      ar: 'معالج وظيفي خبير في إعادة التأهيل المهني وسوق العمل. يساعد الأشخاص ذوي الإعاقات على الاندماج في سوق العمل.',
      en: 'OT expert in vocational rehabilitation and labour market integration, helping people with disabilities re-enter work.',
    },
    photo: 'https://i.pravatar.cc/150?u=moshe-dvir',
    mohRegistrationNumber: 'MOH-55678',
    specialisations: ['vocational', 'mental-health'],
    languages: ['he', 'en'],
    location: { type: 'Point' as const, coordinates: [34.7913, 31.2520], city: 'באר שבע', address: 'רחוב קק"ל 40, באר שבע' },
    sessionTypes: ['in-person', 'telehealth'],
    insuranceAccepted: ['clalit', 'meuhedet', 'private'],
    feeRange: { min: 350, max: 400, currency: 'ILS' as const },
    contactEmail: 'moshe.dvir@therapio.co.il',
    contactPhone: '052-556-6778',
    subscriptionTier: 'free' as const,
    isFeatured: false,
    isAcceptingPatients: true,
  },
  {
    slug: 'shira-landau',
    displayName: { he: 'שירה לנדאו', ar: 'شيرا لانداو', en: 'Shira Landau' },
    bio: {
      he: 'מרפאה בעיסוק בתחום בריאות הנפש ופסיכיאטריה. מתמחה בהפרעות אכילה, PTSD ושיקום לאחר אשפוז פסיכיאטרי.',
      ar: 'معالجة وظيفية في مجال الصحة النفسية متخصصة في اضطرابات الأكل وPTSD.',
      en: 'OT in mental health and psychiatry, specialising in eating disorders, PTSD, and post-psychiatric-hospitalisation rehabilitation.',
    },
    photo: 'https://i.pravatar.cc/150?u=shira-landau',
    mohRegistrationNumber: 'MOH-66789',
    specialisations: ['mental-health'],
    languages: ['he', 'en'],
    location: { type: 'Point' as const, coordinates: [34.8983, 32.1663], city: 'רמת גן', address: 'רחוב ביאליק 15, רמת גן' },
    sessionTypes: ['in-person', 'telehealth'],
    insuranceAccepted: ['maccabi', 'meuhedet', 'leumit', 'private'],
    feeRange: { min: 400, max: 460, currency: 'ILS' as const },
    contactEmail: 'shira.landau@therapio.co.il',
    contactPhone: '054-667-7889',
    subscriptionTier: 'premium' as const,
    isFeatured: false,
    isAcceptingPatients: true,
  },
  {
    slug: 'avi-nachshon',
    displayName: { he: 'אבי נחשון', ar: 'أفي ناحشون', en: 'Avi Nachshon' },
    bio: {
      he: 'מרפא בעיסוק בתחום גריאטריה ודמנציה. מתמחה בפרקינסון ואלצהיימר ובהתאמת הסביבה לשמירה על עצמאות.',
      ar: 'معالج وظيفي في مجال رعاية كبار السن والخرف. متخصص في مرضى باركنسون والزهايمر.',
      en: 'OT in geriatrics and dementia, specialising in Parkinson\'s, Alzheimer\'s and environmental adaptations for independence.',
    },
    photo: 'https://i.pravatar.cc/150?u=avi-nachshon',
    mohRegistrationNumber: 'MOH-77890',
    specialisations: ['geriatrics', 'neurological'],
    languages: ['he', 'ru', 'en'],
    location: { type: 'Point' as const, coordinates: [34.9024, 32.0819], city: 'פתח תקווה', address: 'רחוב אחד העם 88, פתח תקווה' },
    sessionTypes: ['in-person', 'home-visit'],
    insuranceAccepted: ['clalit', 'maccabi', 'leumit', 'private'],
    feeRange: { min: 370, max: 420, currency: 'ILS' as const },
    contactEmail: 'avi.nachshon@therapio.co.il',
    contactPhone: '050-778-8900',
    subscriptionTier: 'free' as const,
    isFeatured: false,
    isAcceptingPatients: true,
  },
  {
    slug: 'maya-reuveni',
    displayName: { he: 'מיה ראובני', ar: 'مايا رئوفيني', en: 'Maya Reuveni' },
    bio: {
      he: 'מרפאה בעיסוק ילדים עם ניסיון בשיקום אחרי פציעות אורתופדיות. מסייעת לילדים לחזור לפעילות יומיומית ולמשחק.',
      ar: 'معالجة وظيفية للأطفال بخبرة في إعادة التأهيل بعد الإصابات العظمية.',
      en: 'Paediatric OT specialising in post-orthopedic rehabilitation, helping children return to daily activities and play.',
    },
    photo: 'https://i.pravatar.cc/150?u=maya-reuveni',
    mohRegistrationNumber: 'MOH-88901',
    specialisations: ['paediatrics', 'hand-therapy'],
    languages: ['he', 'en'],
    location: { type: 'Point' as const, coordinates: [34.9896, 32.7940], city: 'חיפה', address: 'רחוב הגפן 5, חיפה' },
    sessionTypes: ['in-person', 'telehealth'],
    insuranceAccepted: ['clalit', 'maccabi', 'private'],
    feeRange: { min: 380, max: 420, currency: 'ILS' as const },
    contactEmail: 'maya.reuveni@therapio.co.il',
    contactPhone: '052-889-9001',
    subscriptionTier: 'free' as const,
    isFeatured: false,
    isAcceptingPatients: false,
  },
  {
    slug: 'dan-zarchi',
    displayName: { he: 'דן זרחי', ar: 'دان زارحي', en: 'Dan Zarchi' },
    bio: {
      he: 'מרפא בעיסוק בתחום השיקום הקוגניטיבי. מתמחה בשיקום אחרי פגיעת מוח, ניהול זמן, זיכרון וכישורי ארגון.',
      ar: 'معالج وظيفي في مجال إعادة التأهيل الإدراكي. متخصص في إعادة التأهيل بعد إصابات الدماغ.',
      en: 'OT in cognitive rehabilitation, specialising in post-brain-injury recovery, time management, memory, and executive function.',
    },
    photo: 'https://i.pravatar.cc/150?u=dan-zarchi',
    mohRegistrationNumber: 'MOH-99012',
    specialisations: ['neurological', 'mental-health'],
    languages: ['he', 'en'],
    location: { type: 'Point' as const, coordinates: [34.7818, 32.0853], city: 'תל אביב', address: 'רחוב אלנבי 90, תל אביב' },
    sessionTypes: ['in-person', 'telehealth'],
    insuranceAccepted: ['maccabi', 'meuhedet', 'leumit', 'private'],
    feeRange: { min: 420, max: 480, currency: 'ILS' as const },
    contactEmail: 'dan.zarchi@therapio.co.il',
    contactPhone: '054-990-0112',
    subscriptionTier: 'premium' as const,
    isFeatured: false,
    isAcceptingPatients: true,
  },
  {
    slug: 'rachel-stern',
    displayName: { he: 'רחל שטרן', ar: 'راحيل ستيرن', en: 'Rachel Stern' },
    bio: {
      he: 'מרפאה בעיסוק המתמחה בגישת SI (אינטגרציה חושית) לפי Ayres לטיפול בילדים. בעלת הסמכה בינלאומית.',
      ar: 'معالجة وظيفية متخصصة في نهج التكامل الحسي وفق Ayres لعلاج الأطفال. حاصلة على اعتماد دولي.',
      en: 'OT specialising in Ayres Sensory Integration (ASI) for children, internationally certified. Works with SPD and autism spectrum.',
    },
    photo: 'https://i.pravatar.cc/150?u=rachel-stern',
    mohRegistrationNumber: 'MOH-10023',
    specialisations: ['sensory-processing', 'paediatrics'],
    languages: ['he', 'en'],
    location: { type: 'Point' as const, coordinates: [34.7818, 32.0853], city: 'תל אביב', address: 'רחוב נחלת בנימין 30, תל אביב' },
    sessionTypes: ['in-person'],
    insuranceAccepted: ['maccabi', 'leumit', 'private'],
    feeRange: { min: 450, max: 500, currency: 'ILS' as const },
    contactEmail: 'rachel.stern@therapio.co.il',
    contactPhone: '050-100-2234',
    subscriptionTier: 'premium' as const,
    isFeatured: true,
    isAcceptingPatients: true,
  },
  {
    slug: 'tal-sela',
    displayName: { he: 'טל סלע', ar: 'طال سيلاع', en: 'Tal Sela' },
    bio: {
      he: 'מרפאה בעיסוק בתחום שיקום נוירולוגי עם התמחות ב-Virtual Reality לשיקום. חוקרת ומפתחת שיטות טיפול חדשניות.',
      ar: 'معالجة وظيفية في مجال إعادة التأهيل العصبي مع تخصص في الواقع الافتراضي للعلاج.',
      en: 'OT in neurological rehabilitation with a speciality in VR-assisted therapy. Researcher and developer of innovative treatment methods.',
    },
    photo: 'https://i.pravatar.cc/150?u=tal-sela',
    mohRegistrationNumber: 'MOH-10124',
    specialisations: ['neurological'],
    languages: ['he', 'en'],
    location: { type: 'Point' as const, coordinates: [34.8983, 32.1663], city: 'רמת גן', address: 'שדרות ירושלים 120, רמת גן' },
    sessionTypes: ['in-person', 'telehealth'],
    insuranceAccepted: ['clalit', 'maccabi', 'private'],
    feeRange: { min: 440, max: 500, currency: 'ILS' as const },
    contactEmail: 'tal.sela@therapio.co.il',
    contactPhone: '052-101-2345',
    subscriptionTier: 'free' as const,
    isFeatured: false,
    isAcceptingPatients: true,
  },
];

async function seed() {
  console.log(`Connecting to ${MONGODB_URI}...`);
  await mongoose.connect(MONGODB_URI);
  console.log('Connected.');

  let created = 0;
  let updated = 0;

  for (const p of profiles) {
    const result = await OTProfile.updateOne(
      { slug: p.slug },
      { $set: p },
      { upsert: true }
    );
    if (result.upsertedCount) created++;
    else if (result.modifiedCount) updated++;
  }

  console.log(`Seed complete: ${created} created, ${updated} updated, ${profiles.length} total.`);
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
